#+OPTIONS: html-postamble:nil html-preamble:nil
#+AUTHOR:
#+TITLE: NODGUI

* Important note: This branch of NODGUI is highly experimental, API could change and even more bugs can appears.

* NODGUI

  /"No Drama GUI"/

  Common Lisp bindings for the Tk GUI toolkit.

* Dependency

** Programs

 - TCL/TK interpreter (version >= 8.6)
   https://www.tcl.tk

** Lisp libraries

 - alexandria;
 - cl-ppcre-unicode;
 - cl-lex;
 - cl-yacc;
 - clunit2;
 - cl-colors2;
 - named-readtables.

All of the above libraries are available on quicklisp.

** TCL/TK libraries (optional)

- TKlib
  https://core.tcl-lang.org/tklib/home

* Installing

  1. install the tk interpreter (example on a Debian system follows)
  #+BEGIN_SRC sh
  # apt-get install tk
  #+END_SRC

  2. optionally install tklib
  #+BEGIN_SRC sh
  # apt-get install tklib
  #+END_SRC

  3. open a REPL and type
  #+BEGIN_SRC lisp
  (ql:quickload "nodgui")
  #+END_SRC

  4. try it!
  #+BEGIN_SRC lisp
  (nodgui.demo::demo)
  #+END_SRC

* Documentation
   please follow
   [[https://www.autistici.org/interzona/nodgui.html][this link for documentation and news]].

* License

 This software is Copyright (c) 2003-2010  Peter Herth <herth@peter-herth.de>
 Portions Copyright (c) 2005-2010 Thomas F. Burdick
 Portions Copyright (c) 2006-2010 Cadence Design Systems
 Portions Copyright (c) 2010 Daniel Herring
 Portions Copyright (c) 2018,2019,2020 cage

 The authors grant you the rights to distribute
 and use this software as governed by the terms
 of the Lisp Lesser GNU Public License
 (http://opensource.franz.com/preamble.html),
 known as the LLGPL.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
