#+OPTIONS: html-postamble:nil html-preamble:nil
#+AUTHOR:
#+TITLE: NODGUI

* NODGUI

  /"No Drama GUI"/

  Common Lisp bindings for the Tk GUI toolkit.

** important note:

   Version ~0.4.0~ broke the user API, see
   [[https://www.autistici.org/interzona/nodgui.html#orgb470f4b][here]] for more information about how your code is affected and how to fix it.

* Dependency

** Programs

 - TCL/TK interpreter (version >= 8.6)
   https://www.tcl.tk

** Lisp libraries

 - alexandria;
 - cl-ppcre-unicode;
 - esrap
 - clunit2;
 - cl-colors2;
 - named-readtables.

All of the above libraries are available on quicklisp.

** TCL/TK libraries (optional)

- TKlib
  https://core.tcl-lang.org/tklib/home

- tkimg
  https://sourceforge.net/projects/tkimg/

* Installing

  1. install the tk interpreter (example on a Debian system follows)
  #+BEGIN_SRC sh
  # apt-get install tk
  #+END_SRC

  2. optionally install tklib
  #+BEGIN_SRC sh
  # apt-get install tklib
  #+END_SRC

  3. optionally install tkimg

  #+BEGIN_SRC sh
  # apt-get install libtk-img
  #+END_SRC

  4. open a REPL and type
  #+BEGIN_SRC lisp
  (ql:quickload "nodgui")
  #+END_SRC

  5. try it!
  #+BEGIN_SRC lisp
  (nodgui.demo::demo)
  #+END_SRC

* Documentation
   please follow
   [[https://www.autistici.org/interzona/nodgui.html][this link for documentation and news]].

* License

 This software is Copyright (c) 2003-2010  Peter Herth <herth@peter-herth.de>
 Portions Copyright (c) 2005-2010 Thomas F. Burdick
 Portions Copyright (c) 2006-2010 Cadence Design Systems
 Portions Copyright (c) 2010 Daniel Herring
 Portions Copyright © cage

 The authors grant you the rights to distribute
 and use this software as governed by the terms
 of the Lisp Lesser GNU Public License
 (http://opensource.franz.com/preamble.html),
 known as the LLGPL.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

** Themes

The themes definitions found in the ~themes/~ subdirectory are
distributed with many different license, please carefully check the file
~LICENSE.org~ in each theme's subdirectory (e.g [[./themes/yaru/LICENSE.org]]) for more information.

* Acknowledgment

My (cage) deep thanks to Tim Holliefield <tholliefield [at] online.de>, for all the suggestions and help about implementing the widgets styles management.
